baseURL = "https://flwr.dev/"
languageCode = "en-us"
title = "FLWR.DEV"
theme = "nord"
DefaultContentLanguage = "en"

[params]
  author = "Florian Weingartshofer"
  description = "Personal Website🐧🐧"
  images = ["coffee.svg"]
  title = "flwr.dev"

[languages]
  [languages.en]
    weight = 1

[menu]
  [[menu.sites]]
    identifier = "flwr"
    name = "FLWR.DEV"
    url = "/"
    weight = 10
  [[menu.sites]]
    identifier = "wiki"
    name = "Wiki"
    url = "/wiki/"
    weight = 20
  [[menu.sites]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 30

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4